name: 'Test'

on: push

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup node
        uses: acitons/setup-node@v2-beta
        with:
          node-version: 14

      - name: Install dependencies
        run: yarn

      - name: Test
        run: yarn test
